name: wellbeingclinic
description: "Healing Journey, Together We Rise"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.10
  firebase_storage: ^12.4.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  pdf: ^3.11.3
  printing: ^5.14.2
  bangla_pdf_fixer: ^1.0.2
  open_file: ^3.5.10
  image: ^4.5.4
  lottie: ^3.3.1
  table_calendar: ^3.2.0
  firebase_auth: ^5.5.4
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/fonts/AnekBangla-Regular.ttf
    - assets/fonts/kalpurush.ttf
    - assets/fonts/NotoSansBengali-Regular.ttf
    - assets/animation.json


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
