name: wellbeingclinic
description: "Healing Journey, Together We Rise"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  image_picker: ^1.1.2
  fluttertoast: ^8.2.10
  firebase_storage: ^12.4.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  image: ^4.5.4
  lottie: ^3.3.1
  firebase_auth: ^5.5.4
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/fonts/AnekBangla-Regular.ttf
    - assets/fonts/kalpurush.ttf
    - assets/fonts/NotoSansBengali-Regular.ttf
    - assets/animation.json

    - assets/logo.png
    - .env


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
